{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.barrysolomon",
    "module": "mobile-instrumentation-screen",
    "version": "0.5.2-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-core",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-instrumentation-screen-0.5.2-alpha.aar",
          "url": "mobile-instrumentation-screen-0.5.2-alpha.aar",
          "size": 11621,
          "sha512": "01e11393c08ca8a8891907f2f20f8ce87d5499d563157f630241e1a7a7f83bf85b4d429b2ef58dedfcaf7bcd8ff2f32ac673630920da7c2271264f2b904c2f70",
          "sha256": "06b3df33ad41e79e266e54fc0a57c0f9068f66e07c1a3f2e19f3fa5a4528d468",
          "sha1": "709900c445a0d6391f04c97a5744bcb7f535ab40",
          "md5": "523b7e99ee47af514a610c2ca436b950"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-core",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-instrumentation-screen-0.5.2-alpha.aar",
          "url": "mobile-instrumentation-screen-0.5.2-alpha.aar",
          "size": 11621,
          "sha512": "01e11393c08ca8a8891907f2f20f8ce87d5499d563157f630241e1a7a7f83bf85b4d429b2ef58dedfcaf7bcd8ff2f32ac673630920da7c2271264f2b904c2f70",
          "sha256": "06b3df33ad41e79e266e54fc0a57c0f9068f66e07c1a3f2e19f3fa5a4528d468",
          "sha1": "709900c445a0d6391f04c97a5744bcb7f535ab40",
          "md5": "523b7e99ee47af514a610c2ca436b950"
        }
      ]
    }
  ]
}
