{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.barrysolomon",
    "module": "mobile-instrumentation-screenshot",
    "version": "0.9.0-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-core",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-instrumentation-screenshot-0.9.0-beta.aar",
          "url": "mobile-instrumentation-screenshot-0.9.0-beta.aar",
          "size": 20995,
          "sha512": "b1ac9986ed976eca0253c9519cd033c4c3a3f773134f08027152cf4859519edfce0729891b53d931d833c3c1c783aa529093c72652505a885fb9d0c98ee3d691",
          "sha256": "445d13dff2b4352f600027eaa8ae8afcd565d9670f417b97f5e4a7f98c90db63",
          "sha1": "26da7f230ed6f3e879d46ccd22993e7fcd97a569",
          "md5": "887eafa44bbf47594439180dab239e75"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-core",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-instrumentation-screenshot-0.9.0-beta.aar",
          "url": "mobile-instrumentation-screenshot-0.9.0-beta.aar",
          "size": 20995,
          "sha512": "b1ac9986ed976eca0253c9519cd033c4c3a3f773134f08027152cf4859519edfce0729891b53d931d833c3c1c783aa529093c72652505a885fb9d0c98ee3d691",
          "sha256": "445d13dff2b4352f600027eaa8ae8afcd565d9670f417b97f5e4a7f98c90db63",
          "sha1": "26da7f230ed6f3e879d46ccd22993e7fcd97a569",
          "md5": "887eafa44bbf47594439180dab239e75"
        }
      ]
    }
  ]
}
