{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.barrysolomon",
    "module": "mobile",
    "version": "0.9.0-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-core",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-lifecycle",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-screen",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-scroll",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-text-input",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-back-press",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-freeze",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-tap",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-errors",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-network",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-vitals",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-screenshot",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-wireframe",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-compose-click",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-compose-navigation",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-screen-orientation",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-database",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-file-io",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-timber",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-system-events",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.58.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.58.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-logs",
          "version": {
            "requires": "1.58.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-0.9.0-beta.aar",
          "url": "mobile-0.9.0-beta.aar",
          "size": 599338,
          "sha512": "243737cf5610d4e3ca305b0e1e33d033a2664afbc36dde2de072dde9293c054628e8f3739b2d11bf3a5cb43ad2418359cff90005d312de55cccf90824446f490",
          "sha256": "c1cbe3726d0917608bc181c5d2a96377b4b25098a22b06dc7b22b3b40cc2f272",
          "sha1": "d695ded66bdfae5b8418c50381d74c85872a9963",
          "md5": "deb6c86d4e4db9e2dac322184cf73288"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp",
          "version": {
            "requires": "1.58.0"
          }
        },
        {
          "group": "io.opentelemetry.semconv",
          "module": "opentelemetry-semconv",
          "version": {
            "requires": "1.39.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "net.zetetic",
          "module": "sqlcipher-android",
          "version": {
            "requires": "4.6.1"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-core",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-lifecycle",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-screen",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-scroll",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-text-input",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-back-press",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-freeze",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-tap",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-errors",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-network",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-vitals",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-screenshot",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-wireframe",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-compose-click",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-compose-navigation",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-screen-orientation",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-database",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-file-io",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-timber",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-system-events",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.58.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.58.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-logs",
          "version": {
            "requires": "1.58.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-0.9.0-beta.aar",
          "url": "mobile-0.9.0-beta.aar",
          "size": 599338,
          "sha512": "243737cf5610d4e3ca305b0e1e33d033a2664afbc36dde2de072dde9293c054628e8f3739b2d11bf3a5cb43ad2418359cff90005d312de55cccf90824446f490",
          "sha256": "c1cbe3726d0917608bc181c5d2a96377b4b25098a22b06dc7b22b3b40cc2f272",
          "sha1": "d695ded66bdfae5b8418c50381d74c85872a9963",
          "md5": "deb6c86d4e4db9e2dac322184cf73288"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mobile-0.9.0-beta-sources.jar",
          "url": "mobile-0.9.0-beta-sources.jar",
          "size": 193946,
          "sha512": "0f3ae9cecd52ab91324e673bccca0451c507c945029d2cb6b0e9ef594ef3f788b4ebcd2f935b1a341e2a3b6cba734dbd13c025a299ee8900d18aa3e263f9994f",
          "sha256": "1a0d5b12739533a078bb0e53e0272a0940719ede7a5063ae67fb0fc37745f92b",
          "sha1": "30178e9b2f6e642e7c48a815ce68f2255bfb6bda",
          "md5": "d2e7e72c7400086df95f4267cad5bc24"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mobile-0.9.0-beta-javadoc.jar",
          "url": "mobile-0.9.0-beta-javadoc.jar",
          "size": 859933,
          "sha512": "6fd366e496828f4423a589a0e73c30d40312296a4fe9f2373f098c5bf6d9382de740ded432ca2437614bc8d5bb4db349f38f79520bb32dbba95a2edadb3b9002",
          "sha256": "ab38e25cca12c3366d63fc5f08bdbc09c82e549a127bd58fceafcd63948abc84",
          "sha1": "ad955efda6ef363237bf86257e5310648a52fc88",
          "md5": "2082f769ddeb423588d3249d4a029539"
        }
      ]
    }
  ]
}
