{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.barrysolomon",
    "module": "mobile-instrumentation-compose-navigation",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-instrumentation-compose-navigation-1.0.0.aar",
          "url": "mobile-instrumentation-compose-navigation-1.0.0.aar",
          "size": 7464,
          "sha512": "f75c5d0b241c5ece253ff94ed7bd48b938a790bb2a1057a33445428606333cffe38a3f755bdec15a4f762bfe9cd3e21b569cf2eb9fb908248b58677ea0964895",
          "sha256": "2bc5465499d203e7c9d83586f1c4146189e5acb175dd3a9e8e38f56e8ecb4ffe",
          "sha1": "4e898466fd9ac80495b2b215eeea8464b26cf072",
          "md5": "6c7712b610c43516f1da759fa472b880"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-instrumentation-compose-navigation-1.0.0.aar",
          "url": "mobile-instrumentation-compose-navigation-1.0.0.aar",
          "size": 7464,
          "sha512": "f75c5d0b241c5ece253ff94ed7bd48b938a790bb2a1057a33445428606333cffe38a3f755bdec15a4f762bfe9cd3e21b569cf2eb9fb908248b58677ea0964895",
          "sha256": "2bc5465499d203e7c9d83586f1c4146189e5acb175dd3a9e8e38f56e8ecb4ffe",
          "sha1": "4e898466fd9ac80495b2b215eeea8464b26cf072",
          "md5": "6c7712b610c43516f1da759fa472b880"
        }
      ]
    }
  ]
}
