{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.barrysolomon",
    "module": "mobile-instrumentation-system-events",
    "version": "0.5.2-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-core",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-instrumentation-system-events-0.5.2-alpha.aar",
          "url": "mobile-instrumentation-system-events-0.5.2-alpha.aar",
          "size": 6957,
          "sha512": "6745b342f32e12ee4924ab4c625a999b07c18505e0ff11cbb0a716fc049cfcb38afe7b86a721a2fca167cd344feec0f9be2f45f78c78e150db14fd8b9a30a460",
          "sha256": "ba5341276d0d32a2a42972755e87d58e0e638fa88ae478117ec22b677723a1c8",
          "sha1": "41cabcb2d47cfb2c41ff59b5ee0906b29c153c1f",
          "md5": "4bf3d8dd75c5184ba1de76d215ed139d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-core",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-instrumentation-system-events-0.5.2-alpha.aar",
          "url": "mobile-instrumentation-system-events-0.5.2-alpha.aar",
          "size": 6957,
          "sha512": "6745b342f32e12ee4924ab4c625a999b07c18505e0ff11cbb0a716fc049cfcb38afe7b86a721a2fca167cd344feec0f9be2f45f78c78e150db14fd8b9a30a460",
          "sha256": "ba5341276d0d32a2a42972755e87d58e0e638fa88ae478117ec22b677723a1c8",
          "sha1": "41cabcb2d47cfb2c41ff59b5ee0906b29c153c1f",
          "md5": "4bf3d8dd75c5184ba1de76d215ed139d"
        }
      ]
    }
  ]
}
