{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.barrysolomon",
    "module": "mobile-instrumentation-timber",
    "version": "0.9.0-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-core",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-instrumentation-timber-0.9.0-beta.aar",
          "url": "mobile-instrumentation-timber-0.9.0-beta.aar",
          "size": 5255,
          "sha512": "6ce87290cef91bff580cdcf54b4d0fc1371ce7ff086bbe3c10f4f10028a0a8182b4a780b41f549014cecd4257b1019f3749d918dc9a23b47bb912c75515edc1c",
          "sha256": "53feaa82388404e68aafd9ca32388a2ffb9a4afc91b2f3e3f495a4719f02080d",
          "sha1": "b977e9a91c3990c812360a4705fc81a63014ee85",
          "md5": "5a49a3d0f7e00694c3d98a19df04b842"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-core",
          "version": {
            "requires": "0.9.0-beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-instrumentation-timber-0.9.0-beta.aar",
          "url": "mobile-instrumentation-timber-0.9.0-beta.aar",
          "size": 5255,
          "sha512": "6ce87290cef91bff580cdcf54b4d0fc1371ce7ff086bbe3c10f4f10028a0a8182b4a780b41f549014cecd4257b1019f3749d918dc9a23b47bb912c75515edc1c",
          "sha256": "53feaa82388404e68aafd9ca32388a2ffb9a4afc91b2f3e3f495a4719f02080d",
          "sha1": "b977e9a91c3990c812360a4705fc81a63014ee85",
          "md5": "5a49a3d0f7e00694c3d98a19df04b842"
        }
      ]
    }
  ]
}
