{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.barrysolomon",
    "module": "mobile",
    "version": "0.5.2-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-core",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-lifecycle",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-screen",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-scroll",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-text-input",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-back-press",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-freeze",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-tap",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-errors",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-network",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-vitals",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-screenshot",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-wireframe",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-compose-click",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-screen-orientation",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-database",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-file-io",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-timber",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-system-events",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.58.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.58.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-logs",
          "version": {
            "requires": "1.58.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-0.5.2-alpha.aar",
          "url": "mobile-0.5.2-alpha.aar",
          "size": 591029,
          "sha512": "46d5d600b66c9cb46e1fd5dfaea58bd8b2d489c39220ab7b6324dea8654d6e2054a3fc61d0c73fcb7d864ead0cfe2d8c077cb7890b022efc9304dee8f78e1d26",
          "sha256": "8922e6a0283826cc15c251488d0e89cb6674613579269f56be9ef265b244ba09",
          "sha1": "5dc2a60864d84c8b8cb817c9dfe4a4b83d3f635d",
          "md5": "5f04ee9c85f0177d52272577152e4ff9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp",
          "version": {
            "requires": "1.58.0"
          }
        },
        {
          "group": "io.opentelemetry.semconv",
          "module": "opentelemetry-semconv",
          "version": {
            "requires": "1.39.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "net.zetetic",
          "module": "sqlcipher-android",
          "version": {
            "requires": "4.6.1"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-core",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-lifecycle",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-screen",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-scroll",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-text-input",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-back-press",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-freeze",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-tap",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-errors",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-network",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-vitals",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-screenshot",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-wireframe",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-compose-click",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-screen-orientation",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-database",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-file-io",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-timber",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-instrumentation-system-events",
          "version": {
            "requires": "0.5.2-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.58.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.58.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-logs",
          "version": {
            "requires": "1.58.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-0.5.2-alpha.aar",
          "url": "mobile-0.5.2-alpha.aar",
          "size": 591029,
          "sha512": "46d5d600b66c9cb46e1fd5dfaea58bd8b2d489c39220ab7b6324dea8654d6e2054a3fc61d0c73fcb7d864ead0cfe2d8c077cb7890b022efc9304dee8f78e1d26",
          "sha256": "8922e6a0283826cc15c251488d0e89cb6674613579269f56be9ef265b244ba09",
          "sha1": "5dc2a60864d84c8b8cb817c9dfe4a4b83d3f635d",
          "md5": "5f04ee9c85f0177d52272577152e4ff9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mobile-0.5.2-alpha-sources.jar",
          "url": "mobile-0.5.2-alpha-sources.jar",
          "size": 188947,
          "sha512": "a7a8b627937a54988f55256e8b737e3781dcfc75de6a3032a5373905bba8b1df5e5ff11022bf91df3dc1659c936964de0656f2132c55f69183e94fe8b88102f9",
          "sha256": "29f9337e70ce012fcda967d8f2e304f767964b28a072dff510dddf565b66a6c7",
          "sha1": "2ed139f6c8dcfb1c92d89ccf3cc93840fb62b266",
          "md5": "522b0204fac1817bd95c68bc321d5140"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mobile-0.5.2-alpha-javadoc.jar",
          "url": "mobile-0.5.2-alpha-javadoc.jar",
          "size": 844137,
          "sha512": "0cb33dc2044d28c699d8f9729adf13385032f53da8f87d19f8c32f6123455ca6194cfe18da3840bb1adefb84676fc73719a45fd85c976f61a5e0072b02b38481",
          "sha256": "174d1bbdee1718f0eefead801660a59488763bfeff9ee017a9ff90b23b6506cb",
          "sha1": "6b7596c3c7deba642c3e561d0db56d54bcbb37db",
          "md5": "f2f55ea87b8891d035b895769fd51118"
        }
      ]
    }
  ]
}
