{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.barrysolomon",
    "module": "mobile-instrumentation-compose-click",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-instrumentation-compose-click-1.0.0.aar",
          "url": "mobile-instrumentation-compose-click-1.0.0.aar",
          "size": 16983,
          "sha512": "79f02b0a71b32324bcd80aa3e0f0f5af76ffa4fffd0e9ce211f763df73e3d33c7ae2007014e25657c87c1ce03ec4beeaefc3299fe08a7383f76c81b10a703d47",
          "sha256": "c4fe002bd492add3623868eaaba0f92bd613d5535071ad5b3277c53170b141a1",
          "sha1": "2684864af845c1712578e259e5b1c7207f413e24",
          "md5": "2c9ffa9818fdbee802edfd6787193d53"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.barrysolomon",
          "module": "mobile-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "mobile-instrumentation-compose-click-1.0.0.aar",
          "url": "mobile-instrumentation-compose-click-1.0.0.aar",
          "size": 16983,
          "sha512": "79f02b0a71b32324bcd80aa3e0f0f5af76ffa4fffd0e9ce211f763df73e3d33c7ae2007014e25657c87c1ce03ec4beeaefc3299fe08a7383f76c81b10a703d47",
          "sha256": "c4fe002bd492add3623868eaaba0f92bd613d5535071ad5b3277c53170b141a1",
          "sha1": "2684864af845c1712578e259e5b1c7207f413e24",
          "md5": "2c9ffa9818fdbee802edfd6787193d53"
        }
      ]
    }
  ]
}
